FROM quay.io/almalinuxorg/almalinux-bootc:10@sha256:3fcd6be6f217c068a4241ff29209b2311eaa28fc2fa1debd5500dba184d46333

RUN dnf install -y \
        cloud-init cloud-utils-growpart \
        vim \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN systemctl enable cloud-init.service \
                     bootc-fetch-apply-updates.timer

RUN echo export EDITOR=vim >> /etc/profile.d/99-editor-vim.sh

RUN bootc container lint
