FROM quay.io/almalinuxorg/almalinux-bootc:10@sha256:7e5beb82eeec8f233471d48f3eba148c5c1eb37590383d64034f26b502ca7d5a

RUN dnf install -y \
        cloud-init cloud-utils-growpart \
        vim \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN systemctl enable cloud-init.service \
                     bootc-fetch-apply-updates.timer

RUN echo export EDITOR=vim >> /etc/profile.d/99-editor-vim.sh

RUN bootc container lint
