FROM quay.io/almalinuxorg/almalinux-bootc:10@sha256:585a7eaab4e56a11e58042a835c4d328a72d6248019f01ee7fc3746d66a6d113

RUN dnf install -y \
        cloud-init cloud-utils-growpart \
        vim \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN systemctl enable cloud-init.service \
                     bootc-fetch-apply-updates.timer

RUN echo export EDITOR=vim >> /etc/profile.d/99-editor-vim.sh

RUN bootc container lint
