FROM quay.io/almalinuxorg/almalinux-bootc:10@sha256:cd7584328b9e937a6ce5242bac41dab15f2aafa118b8073efc2c44a065f24bf3 AS base-amd64
FROM quay.io/almalinuxorg/almalinux-bootc-rpi:10@sha256:2fb56bdcc5e415295cd949b5888cff2ad4abfdb47266b8336d303ce68dd24882 AS base-arm64

FROM base-${TARGETARCH}

# renovate: datasource=github-tags depName=kubernetes/kubernetes extractVersion=^v(?<version>\d+\.\d+) versioning=regex:^(?<major>\d+)\.(?<minor>\d+)$
ARG k8s_version=1.36

ADD https://jmg.dev/cert.txt /root/.ssh/authorized_keys

COPY modules-load-k8s.conf /etc/modules-load.d/k8s.conf
COPY sysctl-k8s.conf /etc/sysctl.d/k8s.conf



RUN dnf install -y python3-gobject epel-release vim && crb enable

RUN dnf install -y containerd conntrack

RUN mkdir -p /etc/containerd && \
  containerd config default > /etc/containerd/config.toml && \
  sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml && \
  systemctl enable containerd

COPY kubernetes.repo /etc/yum.repos.d/kubernetes.repo

RUN sed -i "s|__K8S_VERSION__|${k8s_version}|g" /etc/yum.repos.d/kubernetes.repo && \
  dnf install -y kubelet kubeadm kubectl && \
  systemctl enable kubelet
